default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host:     <%= ENV.fetch('DB_HOST', 'db') %>
  username: <%= ENV.fetch('DB_USERNAME', 'root') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'password') %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test