version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    networks:
      - default
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    tty: true
    stdin_open: true

volumes:
  bundle:
    driver: local